### ISSUE TITLE
[question] when does it save the items 

### ISSUE THREAD

**Issue by krispyking24** [White-145/nbtvoid#7]
at what point does the mod save the item? when the player opens the chest/container with the item or when its held in the hands/inv of the player

**Comment by White-145** [comment]
Hello! Mod saves items whenever client creates them. If you see an item anywhere, it already was checked/saved by the mod.

**Comment by krispyking24** [comment]
ok thank you the reason i asked was i was going through a map full of nbt interesting things and was using nbt void as a storage for all of them basically
